README.md

This is a tiny documentation fix. No PT story. No test script. Just see the diff.

Fixes tiny documentation mistake

---

.travis.yml
Gulpfile.js
README.md

[100815200](https://www.pivotaltracker.com/story/show/100815200) Replaces CodeShip badge with Travis badge
--
* Deletes CodeShip badge
* Adds ci task to gulp
* Adds .travis.yml
* **Assert that** a Travis badge appears on the README
* **Assert that** the badge is green, i.g., the build passes

100815200 Replaces CodeShip badge with Travis badge

---

README.md

[99634212](https://www.pivotaltracker.com/story/show/99634212) Adds version badge
--
The build will fail *until* PR #33 is merged AND this PR's branch is rebased off of `master`. 
* Adds version badge to README
* **Assert that** version badge appears.

99634212 Adds version badge

---

README.md

* The badges didn't link to anything useful
* This PR fixes that
* For each badge,
* Click on it
* **Assert that** it links to the correct location

Fixes badge links

---

lib/Generator.js
lib/questions.js
lib/templates/other.mustache
lib/templates/provision.sh.mustache
lib/templates/template.mustache

Various fixes and improvements
--
* Fixes ec2.py permissions
* Deletes two wat files
* Improves provision.sh
* Improves keypair question

Various fixes and improvements

---

CHANGELOG.md

Reformats CHANGELOG
--
* Reformats CHANGELOG in accord with [Keep a CHANGELOG](http://keepachangelog.com/)
* View [the reformatted CHANGELOG](https://github.com/radify/radiian/blob/0c92ce265073b29212fba0eb9619422078cd0978/CHANGELOG.md)
* **Assert that** the links work
* **Assert that** it is beautiful
* **Assert that** you are satisfied

Reformats CHANGELOG

---

.codeclimate.yml
.travis.yml
CHANGELOG.md
README.md

Integrates CodeClimate
--
* Adds encrypted CodeClimate repo token to `.travis.yml`
* Adds CodeClimate badge
* Adds `.codeclimate.yml`
* Edits `CHANGELOG`
* None

Integrates CodeClimate

---

CHANGELOG.md
package.json

Updates dependencies
--
* **Assert that** the CI build passes

Updates dependencies

---

CHANGELOG.md
Gulpfile.js
package.json

Adds gulp security task
--
* Installs `gulp-nsp`
* Creates gulp security task
* Adds security task to gulp default task
* Edits `CHANGELOG`
* **Assert that** Travis passes

Adds gulp security task

---

CHANGELOG.md
lib/templates/ansible.cfg.mustache
lib/templates/aws_keys.mustache
lib/templates/destroy-old-nodes.yaml.mustache
lib/templates/ec2.ini.mustache
lib/templates/immutable.yaml.mustache
lib/templates/provision.sh.mustache
lib/templates/tag-old-nodes.yaml.mustache

* Standard mustache tags, {{ }}, escape HTML special characters
* Triple tags, {{{ }}}, disable HTML escaping
* This commit changes the mustache tags in order to disable
the escaping of HTML special characters
* Fixes Issue #57

Disables HTML escaping with new tags

---

lib/templates/ec2.ini.mustache
lib/templates/provision.sh.mustache

* Excludes RDS and ElastiCache
* Prevents instance tagging from halting if execution fails
* Fixes Issues #58 and #59

Tweaks templates

---

CHANGELOG.md
lib/Generator.js

* Simplifies the `generate` function

Simplifies Generator.js

---

lib/templates/destroy-old-nodes.yaml.mustache
lib/templates/provision.sh.mustache
lib/templates/tag-old-nodes.yaml.mustache

We do not need to inject the specific region - instead, we can use Ansible's available facts

Simplifies templates

---

lib/templates/provision.sh.mustache

Fixed issue #76 by removing "ssh-add -l"

Fixed issue #76

---

lib/templates/provision.sh.mustache

Added second cache refresh in the template so Ansible can see the tags.
Fixes #72

Added second cache refresh

---

lib/templates/immutable.yaml.mustache

Changed immutable.yaml to key:value formal
Closes #74

reformatted immutable.yaml

---

lib/templates/ec2.ini.mustache

Uncommented regions_exclude

---

package.json
spec/lib/regexesSpec.js

I added in the specs for awsKey and awsSecret

Regex specs for awsKey and awsSecret

---

lib/Generator.js
lib/questions.js
lib/templates/immutable.yaml.mustache
lib/templates/provision.sh.mustache
spec/lib/questionsSpec.js

Removed unused questions.
Doesn't ask you to pick a tag name for old app. Now it just uses 'old'+AppName.
Converts "-" into "_" for provision.sh
fixes #73, #61, #79 
This achieves what #63 tried to

Removed unused questions

---

lib/questions.js
lib/regexes.js
lib/templates/immutable.yaml.mustache
spec/lib/questionsSpec.js
spec/lib/regexesSpec.js

Added Option to choose between VPC and Classic
Added tests for VPC
fixes #75 and #71

Added VPC support

---

README.md

Adds stuff about the IAM user to docs
Fixes #78

Added IAM user stuff to docs
